In [1]:
import pandas as pd
from preprocess.inputoutput import Reader
import numpy as np
import preprocess.datacleaning as dc

In [2]:
reader = Reader()
df_1 = reader.read_in('./datasets/AppGallery.csv')
df_2 = reader.read_in('./datasets/Purchasing.csv')

In [3]:
df_1 = dc.rename_headers(df_1)
df_1 = dc.drop_unnamed_cols(df_1)

df_2 = dc.rename_headers(df_2)
df_2 = dc.drop_unnamed_cols(df_2)

In [4]:
merged = dc.merge_dfs([df_1, df_2])
merged.info()

<class 'pandas.core.frame.DataFrame'>
Index: 206 entries, 0 to 83
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ticket_id               206 non-null    int64
 1   interaction_id          206 non-null    int64
 2   interaction_date        169 non-null    float64
 3   mailbox                 206 non-null    object
 4   ticket_summary          197 non-null    object
 5   interaction_content     204 non-null    object
 6   innso_typology_ticket_  206 non-null    object
 7   type_1                  206 non-null    object
 8   type_2                  206 non-null    object
 9   type_3                  171 non-null    object
 10  type_4                  163 non-null    object
dtypes: float64(1), int64(2), object(8)
memory usage: 19.3+ KB

In [5]:
df_1[df_1['interaction_content'].isna()]

,ticket_id,interaction_id,interaction_date,mailbox,ticket_summary,interaction_content,innso_typology_ticket_,type_1,type_2,type_3,type_4
63,22964,64204,44805.38125,support.pt@aspiegel.com,Bonus place my Re: support.pt 自动回复: [AppGaller...,NaN,AppGallery &amp; Games / Other Requests,AppGallery &amp; Games,Others,NaN,NaN
65,22964,64204,NaN,support.pt@aspiegel.com,Bonus place my Re: support.pt 自动回复: [AppGaller...,NaN,AppGallery &amp; Games / Other Requests,AppGallery &amp; Games,Others,NaN,NaN

In [6]:
from config import Config as c

na_handler = dc.NaHandler(essential_col_names=c.ESSENTIAL_COLS)

df = na_handler.drop_na_rows(merged)

In [7]:
df = dc.drop_useless_cols(df)
df.head(10000)

,mailbox,ticket_summary,interaction_content,innso_typology_ticket_,type_1,type_2,type_3,type_4
0,support.eu@aspiegel.com,[HUAWEI Music] Problems and Suggestions,Mxxxxx@xxxx.com Отправлено с моего телефона Hu...,AppGallery &amp; Games / Other Requests,AppGallery &amp; Games,Others,NaN,NaN
1,support.pt@aspiegel.com,[AppGallery]Probleme und Vorschläge,Beschreibung Update lässt sich nicht installie...,AppGallery &amp; Games / Suggestions &amp; Fee...,AppGallery &amp; Games,Problem/Fault,AppGallery-Install/Upgrade,Can't update Apps
2,support.pt@aspiegel.com,Re: RE : [AppGallery]Probleme und Vorschläge R...,Danke Nach Neuinstallation der App funktionier...,AppGallery &amp; Games / Suggestions &amp; Fee...,AppGallery &amp; Games,Problem/Fault,AppGallery-Install/Upgrade,Can't update Apps
3,support.pt@aspiegel.com,[AppGallery]Problems and suggestions,Description . Contact information Axxxxx@xxxx.com,AppGallery &amp; Games / Other Requests,AppGallery &amp; Games,Suggestion,AppGallery-Use,Others
5,support.eu@aspiegel.com,Aspiegel Support issue submit,Product: AppGallery & Games Requests: Using Ap...,AppGallery &amp; Games / Information request ...,AppGallery &amp; Games,Suggestion,VIP / Offers / Promotions,Offers / Vouchers / Promotions
...,...,...,...,...,...,...,...,...
79,support.it@Company.com,RE : Pagamenti,"Gentile *****(PER), Grazie per la vostra pazie...",In-App Purchase / Unauthorised charges- bank a...,In-App Purchase,Problem/Fault,Payment issue,Risk Control
80,support.it@Company.com,RE : Rimborso,"Gentile *****(PER), Grazie per la vostra pazie...",In-App Purchase / Unauthorised charges- bank a...,In-App Purchase,Problem/Fault,Payment issue,Risk Control
81,support.it@Company.com,Re: RE : Rimborso,"Gentile *****(PER), la ringrazio per il lavoro...",In-App Purchase / Unauthorised charges- bank a...,In-App Purchase,Problem/Fault,Payment issue,Risk Control
82,support.it@Company.com,RE : Rimborso,"Gentile *****(PER), La ringraziamo per averci ...",In-App Purchase / Unauthorised charges- bank a...,In-App Purchase,Problem/Fault,Payment issue,Risk Control
83,support.eu@Company.com,RE : Company Support issue submit,"Dear Customer, I would like to follow up on th...",In-App Purchase / Cancel /terminate subscription,In-App Purchase,Suggestion,Payment,Subscription cancellation

In [8]:
from preprocess import feature_engineering

fe = feature_engineering.FeatureEngineering(df)
df = fe.process_data(df)

df.head(10000)

,mailbox,innso_typology_ticket_,type_2,type_3,type_4,type_1_AppGallery &amp; Games,type_1_In-App Purchase,interaction_content_and,interaction_content_com,interaction_content_company,...,ticket_summary_refund,ticket_summary_request,ticket_summary_submit,ticket_summary_sugestii,ticket_summary_suggestions,ticket_summary_support,ticket_summary_vip,ticket_summary_și,ticket_summary_предложения,ticket_summary_проблеми
0,4,4,0,-1,-1,True,False,0.000000,0.491906,0.000000,...,0.0,0.0,0.000000,0.0,0.475838,0.000000,0.0,0.0,0.0,0.0
1,7,8,1,0,3,True,False,0.000000,0.443518,0.000000,...,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0
2,7,8,1,0,3,True,False,0.000000,0.344372,0.000000,...,0.0,0.0,0.000000,0.0,0.314019,0.000000,0.0,0.0,0.0,0.0
3,7,4,2,1,10,True,False,0.000000,0.703438,0.000000,...,0.0,0.0,0.000000,0.0,0.533313,0.000000,0.0,0.0,0.0,0.0
4,4,0,2,11,8,True,False,0.258407,0.171394,0.000000,...,0.0,0.0,0.476457,0.0,0.000000,0.465541,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,6,17,1,8,15,False,True,0.000000,0.100381,0.217493,...,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0
191,6,17,1,8,15,False,True,0.000000,0.130221,0.256499,...,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0
192,6,17,1,8,15,False,True,0.000000,0.133325,0.240728,...,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0
193,6,17,1,8,15,False,True,0.000000,0.128890,0.239370,...,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0
194,3,12,2,7,17,False,True,0.202437,0.073849,0.271528,...,0.0,0.0,0.464758,0.0,0.000000,0.454109,0.0,0.0,0.0,0.0