In [1]:
import pandas as pd
from tensorflow.python.ops.parallel_for.pfor import WrappedTensor

from preprocess.inputoutput import Reader, Writer
import numpy as np
import preprocess.datacleaning as dc
from config import Config

In [2]:
config = Config()

In [3]:
reader = Reader()
df_1 = reader.read_in('./datasets/AppGallery.csv')
df_2 = reader.read_in('./datasets/Purchasing.csv')

In [4]:
df_1 = dc.rename_headers(df_1)
df_1 = dc.drop_unnamed_cols(df_1)

df_2 = dc.rename_headers(df_2)
df_2 = dc.drop_unnamed_cols(df_2)

In [5]:
merged = dc.merge_dfs([df_1, df_2])
merged.info()

<class 'pandas.DataFrame'>
Index: 206 entries, 0 to 83
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ticket_id               206 non-null    int64
 1   interaction_id          206 non-null    int64
 2   interaction_date        169 non-null    float64
 3   mailbox                 206 non-null    str
 4   ticket_summary          197 non-null    str
 5   interaction_content     204 non-null    str
 6   innso_typology_ticket_  206 non-null    str
 7   type_1                  206 non-null    str
 8   type_2                  206 non-null    str
 9   type_3                  171 non-null    str
 10  type_4                  163 non-null    str
dtypes: float64(1), int64(2), str(8)
memory usage: 19.3 KB

In [8]:
df_1[df_1['type_3'].isna()]

,ticket_id,interaction_id,interaction_date,mailbox,ticket_summary,interaction_content,innso_typology_ticket_,type_1,type_2,type_3,type_4
0,24310,68365,NaN,support.eu@aspiegel.com,[HUAWEI Music] Problems and Suggestions,Mxxxxx@xxxx.com Отправлено с моего телефона Hu...,AppGallery &amp; Games / Other Requests,AppGallery &amp; Games,Others,NaN,NaN
12,23477,65661,NaN,support.pt@aspiegel.com,Re: support.pt 自动回复: [AppGallery]Problems and ...,"Huawi health On Mon, 5 Sept *****(PHONE), 1:40...",AppGallery &amp; Games / Other Requests,AppGallery &amp; Games,Others,NaN,NaN
15,23395,65482,NaN,support.pt@aspiegel.com,[AppGallery]Problemi e soluzioni,Description In the area where I am (*****(LOC)...,AppGallery &amp; Games / Other Requests,AppGallery &amp; Games,Others,NaN,NaN
16,23230,65024,NaN,support.pt@aspiegel.com,[AppGallery]Проблеми и предложения,Description What's up Contact info *****(PHONE...,AppGallery &amp; Games / Other Requests,AppGallery &amp; Games,Others,NaN,NaN
17,23229,65022,NaN,support.pt@aspiegel.com,[AppGallery]Проблеми и предложения,Описание What's up Информация за контакт *****...,AppGallery &amp; Games / Other Requests,AppGallery &amp; Games,Others,NaN,NaN
18,23212,64982,NaN,support.pt@aspiegel.com,[AppGallery]Проблеми и предложения,OK Описание What's up Информация за контакт **...,AppGallery &amp; Games / Other Requests,AppGallery &amp; Games,Others,NaN,NaN
40,23012,64379,44805.61250,support.pt@aspiegel.com,[AppGallery]Problems and suggestions,Description Haiii buba Contact information BEY...,AppGallery &amp; Games / Other Requests,AppGallery &amp; Games,Others,NaN,NaN
41,23012,64388,44805.61736,support.eu@aspiegel.com,Informations,"Dear Customer, Thank you for contacting *****(...",AppGallery &amp; Games / Other Requests,AppGallery &amp; Games,Others,NaN,NaN
46,23002,64348,44805.57361,support.eu@aspiegel.com,Aspiegel Support issue submit,"Product: In-App Purchase Requests: View, chang...",AppGallery &amp; Games / Other Requests,AppGallery &amp; Games,Others,NaN,NaN
49,22994,64321,44805.53472,support.pt@aspiegel.com,RE : [AppGallery]Problems and suggestions,"Dear Customer, Thank you for contacting *****(...",AppGallery &amp; Games / Suggestions &amp; Fee...,AppGallery &amp; Games,Others,NaN,NaN
51,22983,64268,44805.45764,support.pt@aspiegel.com,RE : [AppGallery]Probleme și sugestii,"Stimate client, Vă mulțumim că ați contactat A...",AppGallery &amp; Games / Other Requests,AppGallery &amp; Games,Others,NaN,NaN
52,22982,64259,44805.44514,support.pt@aspiegel.com,Problems and suggestions متجر التطبيقات]المشاك...,التفاصيل نقل الصادرة. الواردة معلومات التواصل ...,AppGallery &amp; Games / Suggestions &amp; Fee...,AppGallery &amp; Games,Others,NaN,NaN
53,22980,64253,44805.44097,support.eu@aspiegel.com,Aspiegel Support issue submit,Product: Other products Requests: Requests Con...,AppGallery &amp; Games / Unable to claim the p...,AppGallery &amp; Games,Others,NaN,NaN
54,22980,64265,44805.45486,support.de@aspiegel.com,GT3,"Sehr geehrter Herrn *****(PER), Wir empfehlen ...",AppGallery &amp; Games / Unable to claim the p...,AppGallery &amp; Games,Others,NaN,NaN
55,22980,64271,44805.46597,support.de@aspiegel.com,Re: GT3,Es tut mir leid discord habe ich nicht und wer...,AppGallery &amp; Games / Unable to claim the p...,AppGallery &amp; Games,Others,NaN,NaN
56,22980,64280,44805.47292,support.de@aspiegel.com,RE : GT3,"Sehr geehrter Herrn *****(PER), vielen Dank fü...",AppGallery &amp; Games / Unable to claim the p...,AppGallery &amp; Games,Others,NaN,NaN
57,22980,64289,44805.48889,support.de@aspiegel.com,RE : GT3,"Sehr geehrter Herrn *****(PER), ich bedanke mi...",AppGallery &amp; Games / Unable to claim the p...,AppGallery &amp; Games,Others,NaN,NaN
59,22978,64255,44805.44375,support.eu@aspiegel.com,RE : [AppGallery]Problems and suggestions,"Stimate client, Vă mulțumim că ați contactat A...",AppGallery &amp; Games / Suggestions &amp; Fee...,AppGallery &amp; Games,Others,NaN,NaN
62,22972,64242,44805.43056,support.pt@aspiegel.com,RE : [AppGallery]Probleme și sugestii,"Stimate client, Vă mulțumim că ați contactat A...",AppGallery &amp; Games / Other Requests,AppGallery &amp; Games,Others,NaN,NaN
63,22964,64204,44805.38125,support.pt@aspiegel.com,Bonus place my Re: support.pt 自动回复: [AppGaller...,NaN,AppGallery &amp; Games / Other Requests,AppGallery &amp; Games,Others,NaN,NaN
64,22964,64211,44805.39028,support.pt@aspiegel.com,RE : Bonus place my Re: support.pt 自动回复: [AppG...,"Dear Customer, Thank you for contacting *****(...",AppGallery &amp; Games / Other Requests,AppGallery &amp; Games,Others,NaN,NaN
65,22964,64204,NaN,support.pt@aspiegel.com,Bonus place my Re: support.pt 自动回复: [AppGaller...,NaN,AppGallery &amp; Games / Other Requests,AppGallery &amp; Games,Others,NaN,NaN
66,22963,64202,44805.38125,support.pt@aspiegel.com,[AppGallery]Проблемы и предложения,Timestamp: *****(PHONE)-06-28T11:17:39Z Messag...,AppGallery &amp; Games / Other Requests,AppGallery &amp; Games,Others,NaN,NaN
67,22963,64209,44805.38819,support.pt@aspiegel.com,RE : [AppGallery]Проблемы и предложения,"Dear Customer, Thank you for contacting *****(...",AppGallery &amp; Games / Other Requests,AppGallery &amp; Games,Others,NaN,NaN
73,22962,64469,44805.72361,support.eu@aspiegel.com,Reply,"Dear user, Thank you for your cooperation. To ...",AppGallery &amp; Games / Information request ...,AppGallery &amp; Games,Others,NaN,NaN
75,22959,64406,44805.62361,support.pt@aspiegel.com,RE : [AppGallery]Problem och förslag[AppGaller...,"Dear Customer, Thank you for contacting *****(...",AppGallery &amp; Games / Suggestions &amp; Fee...,AppGallery &amp; Games,Others,NaN,NaN
78,22948,64155,44805.33194,support.pt@aspiegel.com,[AppGallery]Problémák és javaslatok,Leírás Versionproblem Névjegy információk xxxx...,AppGallery &amp; Games / Other Requests,AppGallery &amp; Games,Others,NaN,NaN
79,22948,64157,44805.33611,support.pt@aspiegel.com,RE : [AppGallery]Problémák és javaslatok,"Dear Customer, Thank you for contacting *****(...",AppGallery &amp; Games / Other Requests,AppGallery &amp; Games,Others,NaN,NaN
83,22943,64213,44805.39514,support.pt@aspiegel.com,RE : [AppGallery]Problems and suggestions,"Dear customer, Thank you for contacting *****(...",AppGallery &amp; Games / Other Requests,AppGallery &amp; Games,Others,NaN,NaN
102,22909,64407,44805.62361,support.pt@aspiegel.com,RE : [AppGallery]Problémák és javaslatok,"Dear Customer, Thank you for contacting *****(...",AppGallery &amp; Games / Suggestions &amp; Fee...,AppGallery &amp; Games,Others,NaN,NaN
114,22567,64199,44805.37708,support.pt@aspiegel.com,RE : [AppGallery]Probleme și sugestii,"Dear customer, I would like to follow up on th...",AppGallery &amp; Games / Suggestions &amp; Fee...,AppGallery &amp; Games,Others,NaN,NaN
115,22555,64198,44805.37500,support.pt@aspiegel.com,RE : [AppGallery]Problems and suggestions,"Dear customer, I would like to follow up on th...",AppGallery &amp; Games / Suggestions &amp; Fee...,AppGallery &amp; Games,Others,NaN,NaN
116,22481,64456,44805.69444,support.de@aspiegel.com,Collecting more information,"Sehr geehrter Kunde, ich möchte den Fall weite...",AppGallery &amp; Games / Other Requests,AppGallery &amp; Games,Others,NaN,NaN

In [9]:
df = dc.col_rows_to_lowercase(merged)
df.head(100)

,ticket_id,interaction_id,interaction_date,mailbox,ticket_summary,interaction_content,innso_typology_ticket_,type_1,type_2,type_3,type_4
0,24310,68365,NaN,support.eu@aspiegel.com,[huawei music] problems and suggestions,mxxxxx@xxxx.com отправлено с моего телефона hu...,appgallery &amp; games / other requests,appgallery &amp; games,others,NaN,NaN
1,24075,67730,NaN,support.pt@aspiegel.com,[appgallery]probleme und vorschläge,beschreibung update lässt sich nicht installie...,appgallery &amp; games / suggestions &amp; fee...,appgallery &amp; games,problem/fault,appgallery-install/upgrade,can't update apps
2,24075,67762,NaN,support.pt@aspiegel.com,re: re : [appgallery]probleme und vorschläge r...,danke nach neuinstallation der app funktionier...,appgallery &amp; games / suggestions &amp; fee...,appgallery &amp; games,problem/fault,appgallery-install/upgrade,can't update apps
3,23748,66706,NaN,support.pt@aspiegel.com,[appgallery]problems and suggestions,description . contact information axxxxx@xxxx.com,appgallery &amp; games / other requests,appgallery &amp; games,suggestion,appgallery-use,others
4,23740,66684,NaN,support.eu@aspiegel.com,NaN,ho pagato ma l'applicazione non ha funzionato ...,appgallery &amp; games / refund request : app/...,appgallery &amp; games,problem/fault,third party apps,refund
...,...,...,...,...,...,...,...,...,...,...,...
95,22926,64238,44805.42569,support.es1@aspiegel.com,re : puntos huawei,"estimado cliente, gracias por contactar con as...",appgallery &amp; games / huawei points missing,appgallery &amp; games,problem/fault,coupon/gifts/points issues,can't use or acquire
96,22926,64320,44805.53333,support.es1@aspiegel.com,re: re : puntos huawei,buenas tardes contesto a las preguntas solicit...,appgallery &amp; games / huawei points missing,appgallery &amp; games,problem/fault,coupon/gifts/points issues,can't use or acquire
97,22926,64322,44805.53611,support.es1@aspiegel.com,re : puntos huawei,"estimado cliente, muchas gracias por la inform...",appgallery &amp; games / huawei points missing,appgallery &amp; games,problem/fault,coupon/gifts/points issues,can't use or acquire
98,22924,64153,44805.31736,support.eu@aspiegel.com,re: re : refund request,screenshot_*****(phone)_*****(phone)_com.huawe...,appgallery &amp; games / refund request: accid...,appgallery &amp; games,problem/fault,third party apps,refund
99,22924,64303,44805.51042,support.eu@aspiegel.com,re : refund request,"dear customer, thank you for your reply. unfor...",appgallery &amp; games / refund request: accid...,appgallery &amp; games,problem/fault,third party apps,refund

In [10]:
from config import Config

na_handler = dc.NaHandler(essential_col_names=config.ESSENTIAL_COLS)

df = na_handler.drop_na_rows(df)

In [11]:
df = dc.drop_useless_cols(df)
df.head(10000)

,mailbox,ticket_summary,interaction_content,innso_typology_ticket_,type_1,type_2,type_3,type_4
0,support.eu@aspiegel.com,[huawei music] problems and suggestions,mxxxxx@xxxx.com отправлено с моего телефона hu...,appgallery &amp; games / other requests,appgallery &amp; games,others,NaN,NaN
1,support.pt@aspiegel.com,[appgallery]probleme und vorschläge,beschreibung update lässt sich nicht installie...,appgallery &amp; games / suggestions &amp; fee...,appgallery &amp; games,problem/fault,appgallery-install/upgrade,can't update apps
2,support.pt@aspiegel.com,re: re : [appgallery]probleme und vorschläge r...,danke nach neuinstallation der app funktionier...,appgallery &amp; games / suggestions &amp; fee...,appgallery &amp; games,problem/fault,appgallery-install/upgrade,can't update apps
3,support.pt@aspiegel.com,[appgallery]problems and suggestions,description . contact information axxxxx@xxxx.com,appgallery &amp; games / other requests,appgallery &amp; games,suggestion,appgallery-use,others
5,support.eu@aspiegel.com,aspiegel support issue submit,product: appgallery & games requests: using ap...,appgallery &amp; games / information request ...,appgallery &amp; games,suggestion,vip / offers / promotions,offers / vouchers / promotions
...,...,...,...,...,...,...,...,...
79,support.it@company.com,re : pagamenti,"gentile *****(per), grazie per la vostra pazie...",in-app purchase / unauthorised charges- bank a...,in-app purchase,problem/fault,payment issue,risk control
80,support.it@company.com,re : rimborso,"gentile *****(per), grazie per la vostra pazie...",in-app purchase / unauthorised charges- bank a...,in-app purchase,problem/fault,payment issue,risk control
81,support.it@company.com,re: re : rimborso,"gentile *****(per), la ringrazio per il lavoro...",in-app purchase / unauthorised charges- bank a...,in-app purchase,problem/fault,payment issue,risk control
82,support.it@company.com,re : rimborso,"gentile *****(per), la ringraziamo per averci ...",in-app purchase / unauthorised charges- bank a...,in-app purchase,problem/fault,payment issue,risk control
83,support.eu@company.com,re : company support issue submit,"dear customer, i would like to follow up on th...",in-app purchase / cancel /terminate subscription,in-app purchase,suggestion,payment,subscription cancellation

In [12]:
#df = dc.translate_to_en(df)
#writer = Writer()
#writer.write_out(df, './translated_df.csv')
df = reader.read_in('./translated_df.csv')

In [11]:
#df[df['interaction_id'] == 64394]

In [13]:
from preprocess import feature_engineering

fe = feature_engineering.FeatureEngineering(df)
df = fe.process_data()

df.head(10000)

,mailbox,innso_typology_ticket_,type_2,type_3,type_4,type_1_appgallery &amp; games,type_1_in-app purchase,interaction_content_account,interaction_content_cancel,interaction_content_com,...,ticket_summary_refund,ticket_summary_request,ticket_summary_reward,ticket_summary_send,ticket_summary_submit,ticket_summary_subscription,ticket_summary_suggestion,ticket_summary_support,ticket_summary_termination,ticket_summary_vip
0,3,4,0,-1,-1,True,False,0.000000,0.000000,0.404062,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.447357,0.000000,0.0,0.0
1,7,8,1,0,3,True,False,0.000000,0.000000,0.335584,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.559529,0.000000,0.0,0.0
2,7,8,1,0,3,True,False,0.000000,0.000000,0.354059,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.559529,0.000000,0.0,0.0
3,7,4,2,1,10,True,False,0.000000,0.000000,0.580266,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.559529,0.000000,0.0,0.0
4,3,0,2,11,8,True,False,0.000000,0.000000,0.234357,...,0.0,0.0,0.0,0.0,0.488164,0.0,0.000000,0.476980,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,6,17,1,8,15,False,True,0.124066,0.000000,0.168525,...,0.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0
191,6,17,1,8,15,False,True,0.134968,0.173887,0.206251,...,1.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0
192,6,17,1,8,15,False,True,0.134156,0.172841,0.227789,...,1.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0
193,6,17,1,8,15,False,True,0.133382,0.171843,0.226474,...,1.0,0.0,0.0,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.0
194,4,12,2,7,17,False,True,0.053369,0.309410,0.126863,...,0.0,0.0,0.0,0.0,0.491083,0.0,0.000000,0.479832,0.0,0.0