In [1]:
import pandas as pd
from preprocess.inputoutput import Reader
import numpy as np
import preprocess.datacleaning as dc

In [2]:
reader = Reader()
df_1 = reader.read_in('./datasets/AppGallery.csv')
df_2 = reader.read_in('./datasets/Purchasing.csv')

In [3]:
df_1 = dc.rename_headers(df_1)
df_1 = dc.drop_unnamed_cols(df_1)

df_2 = dc.rename_headers(df_2)
df_2 = dc.drop_unnamed_cols(df_2)

In [4]:
merged = dc.merge_dfs([df_1, df_2])
merged.info()

<class 'pandas.DataFrame'>
Index: 206 entries, 0 to 83
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ticket_id               206 non-null    int64
 1   interaction_id          206 non-null    int64
 2   interaction_date        169 non-null    float64
 3   mailbox                 206 non-null    str
 4   ticket_summary          197 non-null    str
 5   interaction_content     204 non-null    str
 6   innso_typology_ticket_  206 non-null    str
 7   type_1                  206 non-null    str
 8   type_2                  206 non-null    str
 9   type_3                  171 non-null    str
 10  type_4                  163 non-null    str
dtypes: float64(1), int64(2), str(8)
memory usage: 19.3 KB

In [5]:
df_1[df_1['interaction_content'].isna()]

,ticket_id,interaction_id,interaction_date,mailbox,ticket_summary,interaction_content,innso_typology_ticket_,type_1,type_2,type_3,type_4
63,22964,64204,44805.38125,support.pt@aspiegel.com,Bonus place my Re: support.pt 自动回复: [AppGaller...,NaN,AppGallery &amp; Games / Other Requests,AppGallery &amp; Games,Others,NaN,NaN
65,22964,64204,NaN,support.pt@aspiegel.com,Bonus place my Re: support.pt 自动回复: [AppGaller...,NaN,AppGallery &amp; Games / Other Requests,AppGallery &amp; Games,Others,NaN,NaN

In [6]:
df = dc.col_rows_to_lowercase(merged)
df.head(100)

,ticket_id,interaction_id,interaction_date,mailbox,ticket_summary,interaction_content,innso_typology_ticket_,type_1,type_2,type_3,type_4
0,24310,68365,NaN,support.eu@aspiegel.com,[huawei music] problems and suggestions,mxxxxx@xxxx.com отправлено с моего телефона hu...,appgallery &amp; games / other requests,appgallery &amp; games,others,NaN,NaN
1,24075,67730,NaN,support.pt@aspiegel.com,[appgallery]probleme und vorschläge,beschreibung update lässt sich nicht installie...,appgallery &amp; games / suggestions &amp; fee...,appgallery &amp; games,problem/fault,appgallery-install/upgrade,can't update apps
2,24075,67762,NaN,support.pt@aspiegel.com,re: re : [appgallery]probleme und vorschläge r...,danke nach neuinstallation der app funktionier...,appgallery &amp; games / suggestions &amp; fee...,appgallery &amp; games,problem/fault,appgallery-install/upgrade,can't update apps
3,23748,66706,NaN,support.pt@aspiegel.com,[appgallery]problems and suggestions,description . contact information axxxxx@xxxx.com,appgallery &amp; games / other requests,appgallery &amp; games,suggestion,appgallery-use,others
4,23740,66684,NaN,support.eu@aspiegel.com,NaN,ho pagato ma l'applicazione non ha funzionato ...,appgallery &amp; games / refund request : app/...,appgallery &amp; games,problem/fault,third party apps,refund
...,...,...,...,...,...,...,...,...,...,...,...
95,22926,64238,44805.42569,support.es1@aspiegel.com,re : puntos huawei,"estimado cliente, gracias por contactar con as...",appgallery &amp; games / huawei points missing,appgallery &amp; games,problem/fault,coupon/gifts/points issues,can't use or acquire
96,22926,64320,44805.53333,support.es1@aspiegel.com,re: re : puntos huawei,buenas tardes contesto a las preguntas solicit...,appgallery &amp; games / huawei points missing,appgallery &amp; games,problem/fault,coupon/gifts/points issues,can't use or acquire
97,22926,64322,44805.53611,support.es1@aspiegel.com,re : puntos huawei,"estimado cliente, muchas gracias por la inform...",appgallery &amp; games / huawei points missing,appgallery &amp; games,problem/fault,coupon/gifts/points issues,can't use or acquire
98,22924,64153,44805.31736,support.eu@aspiegel.com,re: re : refund request,screenshot_*****(phone)_*****(phone)_com.huawe...,appgallery &amp; games / refund request: accid...,appgallery &amp; games,problem/fault,third party apps,refund
99,22924,64303,44805.51042,support.eu@aspiegel.com,re : refund request,"dear customer, thank you for your reply. unfor...",appgallery &amp; games / refund request: accid...,appgallery &amp; games,problem/fault,third party apps,refund

In [7]:
from config import Config as c

na_handler = dc.NaHandler(essential_col_names=c.ESSENTIAL_COLS)

df = na_handler.drop_na_rows(df)

In [8]:
df = dc.drop_useless_cols(df)
df.head(10000)

,mailbox,ticket_summary,interaction_content,innso_typology_ticket_,type_1,type_2,type_3,type_4
0,support.eu@aspiegel.com,[huawei music] problems and suggestions,mxxxxx@xxxx.com отправлено с моего телефона hu...,appgallery &amp; games / other requests,appgallery &amp; games,others,NaN,NaN
1,support.pt@aspiegel.com,[appgallery]probleme und vorschläge,beschreibung update lässt sich nicht installie...,appgallery &amp; games / suggestions &amp; fee...,appgallery &amp; games,problem/fault,appgallery-install/upgrade,can't update apps
2,support.pt@aspiegel.com,re: re : [appgallery]probleme und vorschläge r...,danke nach neuinstallation der app funktionier...,appgallery &amp; games / suggestions &amp; fee...,appgallery &amp; games,problem/fault,appgallery-install/upgrade,can't update apps
3,support.pt@aspiegel.com,[appgallery]problems and suggestions,description . contact information axxxxx@xxxx.com,appgallery &amp; games / other requests,appgallery &amp; games,suggestion,appgallery-use,others
5,support.eu@aspiegel.com,aspiegel support issue submit,product: appgallery & games requests: using ap...,appgallery &amp; games / information request ...,appgallery &amp; games,suggestion,vip / offers / promotions,offers / vouchers / promotions
...,...,...,...,...,...,...,...,...
79,support.it@company.com,re : pagamenti,"gentile *****(per), grazie per la vostra pazie...",in-app purchase / unauthorised charges- bank a...,in-app purchase,problem/fault,payment issue,risk control
80,support.it@company.com,re : rimborso,"gentile *****(per), grazie per la vostra pazie...",in-app purchase / unauthorised charges- bank a...,in-app purchase,problem/fault,payment issue,risk control
81,support.it@company.com,re: re : rimborso,"gentile *****(per), la ringrazio per il lavoro...",in-app purchase / unauthorised charges- bank a...,in-app purchase,problem/fault,payment issue,risk control
82,support.it@company.com,re : rimborso,"gentile *****(per), la ringraziamo per averci ...",in-app purchase / unauthorised charges- bank a...,in-app purchase,problem/fault,payment issue,risk control
83,support.eu@company.com,re : company support issue submit,"dear customer, i would like to follow up on th...",in-app purchase / cancel /terminate subscription,in-app purchase,suggestion,payment,subscription cancellation

In [9]:
df = dc.translate_to_en(df)
df.head(10000)

Translation of 5082 characters is too long for API, truncating to first 4900 words.
Translation of 5304 characters is too long for API, truncating to first 4900 words.
Translation of 6827 characters is too long for API, truncating to first 4900 words.
Translation of 7650 characters is too long for API, truncating to first 4900 words.
Translation of 8691 characters is too long for API, truncating to first 4900 words.
Translation of 8969 characters is too long for API, truncating to first 4900 words.
Translation of 7398 characters is too long for API, truncating to first 4900 words.
Translation of 8420 characters is too long for API, truncating to first 4900 words.
Translation of 8765 characters is too long for API, truncating to first 4900 words.
Translation of 7831 characters is too long for API, truncating to first 4900 words.
Translation of 8948 characters is too long for API, truncating to first 4900 words.
Translation of 5304 characters is too long for API, truncating to first 4900 words.
Translation of 5634 characters is too long for API, truncating to first 4900 words.
Translation of 6073 characters is too long for API, truncating to first 4900 words.
Translation of 7083 characters is too long for API, truncating to first 4900 words.
Translation of 7156 characters is too long for API, truncating to first 4900 words.
Translation of 8847 characters is too long for API, truncating to first 4900 words.
Translation of 22054 characters is too long for API, truncating to first 4900 words.
Translation of 24048 characters is too long for API, truncating to first 4900 words.
Translation of 22054 characters is too long for API, truncating to first 4900 words.
Translation of 5101 characters is too long for API, truncating to first 4900 words.
Translation of 5050 characters is too long for API, truncating to first 4900 words.
Translation of 5378 characters is too long for API, truncating to first 4900 words.
Translation of 6640 characters is too long for API, truncating to first 4900 words.
Translation of 6821 characters is too long for API, truncating to first 4900 words.
Translation of 5597 characters is too long for API, truncating to first 4900 words.
Translation of 5308 characters is too long for API, truncating to first 4900 words.
Translation of 5445 characters is too long for API, truncating to first 4900 words.
Translation of 6384 characters is too long for API, truncating to first 4900 words.
Translation of 7356 characters is too long for API, truncating to first 4900 words.

,mailbox,ticket_summary,interaction_content,innso_typology_ticket_,type_1,type_2,type_3,type_4
0,support.eu@aspiegel.com,huawei music problem suggestion,mxxxxx@xxxx.com send huawei phone,appgallery &amp; games / other requests,appgallery &amp; games,others,NaN,NaN
1,support.pt@aspiegel.com,appgallery]problem suggestion,description update instal contact information ...,appgallery &amp; games / suggestions &amp; fee...,appgallery &amp; games,problem/fault,appgallery-install/upgrade,can't update apps
2,support.pt@aspiegel.com,appgallery]problem suggestion appgallery]probl...,thank reinstall app work perfectly mfg write t...,appgallery &amp; games / suggestions &amp; fee...,appgallery &amp; games,problem/fault,appgallery-install/upgrade,can't update apps
3,support.pt@aspiegel.com,appgallery]problem suggestion,description contact information axxxxx@xxxx.com,appgallery &amp; games / other requests,appgallery &amp; games,suggestion,appgallery-use,others
4,support.eu@aspiegel.com,aspiegel support issue submit,product appgallery game request appgallery i.e...,appgallery &amp; games / information request ...,appgallery &amp; games,suggestion,vip / offers / promotions,offers / vouchers / promotions
...,...,...,...,...,...,...,...,...
190,support.it@company.com,payment,dear thank patience confirm suspicious activit...,in-app purchase / unauthorised charges- bank a...,in-app purchase,problem/fault,payment issue,risk control
191,support.it@company.com,refund,dear thank patience confirm suspicious activit...,in-app purchase / unauthorised charges- bank a...,in-app purchase,problem/fault,payment issue,risk control
192,support.it@company.com,refund,dear thank work await confidently greeting 09/...,in-app purchase / unauthorised charges- bank a...,in-app purchase,problem/fault,payment issue,risk control
193,support.it@company.com,refund,dear thank bring issue question hesitate reply...,in-app purchase / unauthorised charges- bank a...,in-app purchase,problem/fault,payment issue,risk control
194,support.eu@company.com,company support issue submit,dear customer like follow case raise 08/28/***...,in-app purchase / cancel /terminate subscription,in-app purchase,suggestion,payment,subscription cancellation

In [11]:
from preprocess import feature_engineering

fe = feature_engineering.FeatureEngineering(df)
df = fe.process_data()

df.head(10000)

KeyError: "None of [Index(['type_1'], dtype='str')] are in the [columns]"